### ISSUE TITLE
Fix readme reference to jspm package

### ISSUE THREAD

**Issue by plwalters** [PWKad/aurelia-bs-modal#2]
Remove the github:pwkad/ from jspm install

**Comment by lipsitzm** [comment]
You may want to also add that jquery is a dependency, but that definitely becomes obvious fast once you try to load your app after installing it.

**Comment by plwalters** [comment]
True, jQuery is actually a dependency of Bootstrap so it is sort of implied it just should be more explicit, thanks for the note.

**Comment by plwalters** [comment]
Both of these issues should be fixed now.
