### ISSUE TITLE
Update README for loading plugin

### ISSUE THREAD

**Issue by mlaccetti** [PWKad/aurelia-bs-modal#4]
```
// Install the plugin
.plugin('aurelia-bs-modal');
```

should be

```
// Install the plugin
.plugin('pwkad/aurelia-bs-modal');
```

**Comment by plwalters** [comment]
This actually depends on how you jspm install it.  I thought I had fixed that to `jspm install aurelia-bs-modal` but apparently I didn't.  Will update that instead, thanks for the heads up.
