### ISSUE TITLE
stand-alone modal support

### ISSUE THREAD

**Issue by maxgrv** [PWKad/aurelia-bs-modal#5]
Would it be possible to have support for a feature like durandal dialog plugin "showDialog" function that takes a VM (with corresponding view) and instantiates a dialog everywhere in the app (thus without having to place the dialog in a specific view and having the staring viewmodel contain the dialog "showing" property and methods). 

```
 app.showDialog(viewModel, data)
```

It seems to me to be a very elegant approach, as you can reuse dialogs everywhere you want, and the method returns a promise with the dialog result so you can wait for user input or whatever in a very easy and clean way.

This is also independent from the UI library you use.

**Comment by plwalters** [comment]
Yes, you can do this a few different ways - 
1. by supplying a modal at the root (such as app.html) and calling it from your various places around the app.  For now it would be up to you to implement the showDialog method on app.js or somewhere to handle composing it, I'll try to get a sample up soon.
2. This repo and two by @Aaike will be converging as an official repo and offering this ability similar to how Aaike is doing so with a compiler.

**Comment by plwalters** [comment]
Leaving this open for now so we don't forget when merging :)

**Comment by maxgrv** [comment]
Yes we made a simple plugin to implement # 1. The only feature of the old
durandal dialog plugin that is missing (for now) is the ability to nest
dialogs as at the moment we reuse the same dialog element. It should not be
very difficult to implement if need arises though. By the way, we have a
small problem in this plugin as we use polymer modal element but we are
unable to find a way to correctly trigger modal resize after composition is
complete. Does the compose element call a VM function or fire an event when
composition is complete?

**Comment by plwalters** [comment]
@maxgrv Yes the `attached` callback is called.

**Comment by maxgrv** [comment]
@PWKad Thanks, now we got it working flawlessly.

**Comment by plwalters** [comment]
@maxgrv This is now possible with https://github.com/aurelia/dialog so I'm going to leave this repo as is.  If you want to have the same ability please switch over to the official dialog repo.  Feel free to re-open if this doesn't suit your needs and I can move the issue over there or something.
